name: Events Demo 1
on: 
  pull_request:
    types: 
      - opened 
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
  workflow_dispatch: {}
  push: 
    branches:
      - main
      - 'dev*'
      - 'dev-*'
      - 'feat/**'
    paths:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output some_event data
        run: |
          echo "${{ toJSON(github.event) }}" > event.json
          cat event.json
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."